#!/usr/bin/with-contenv bash

cd /app/babybuddy || exit

exec \
    s6-setuidgid abc gunicorn babybuddy.wsgi -b :8000 --log-level=info \
        --worker-tmp-dir=/dev/shm --log-file=- \
        --workers=2 --threads=4 --worker-class=gthread
